function dVdt = dVdt_func(in1,in2)
%dVdt_func
%    dVdt = dVdt_func(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 24.2.
%    11-Sep-2025 12:46:06

K1_1 = in2(1);
K1_2 = in2(3);
K2_1 = in2(2);
K2_2 = in2(4);
x = in1(1,:);
y = in1(2,:);
dVdt = -x.*(K1_1.*x+K2_1.*y)-y.*(K1_2.*x+K2_2.*y);
end
