function out1 = eom_func(t,in2,in3)
%EOM_FUNC
%    OUT1 = EOM_FUNC(T,IN2,IN3)

%    This function was generated by the Symbolic Math Toolbox version 24.2.
%    11-Sep-2025 12:46:06

K1_1 = in3(1);
K1_2 = in3(3);
K2_1 = in3(2);
K2_2 = in3(4);
x = in2(1,:);
y = in2(2,:);
t2 = cos(y);
t3 = sin(x);
t4 = K1_1.*x;
t5 = K1_2.*x;
t6 = K2_1.*y;
t7 = K2_2.*y;
out1 = [-t4-t6;-t5-t7;(t4+t6-t2.*t3.*x).^2./2.0+(t5+t7-t2.*t3.*y).^2./2.0];
end
