function V = V_func(in1,in2)
%V_func
%    V = V_func(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 24.2.
%    11-Sep-2025 12:46:06

x = in1(1,:);
y = in1(2,:);
V = x.^2./2.0+y.^2./2.0;
end
