function V = zermelo_V(in1,in2)
%zermelo_V
%    V = zermelo_V(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 24.2.
%    11-Sep-2025 13:50:28

x = in1(1,:);
y = in1(2,:);
V = x.^2./2.0+y.^2./2.0;
end
